config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :create, :new]
  resources :conversations, only: [:create, :show] do
    resources :messages, only: [:create]
  end

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :conversations_users
  has_many :participants, through: :conversations_users, source: :user
  has_many :messages

  # TODO: remove description column
end

app/models/conversations_user.rb
# TODO: rename to ConversationUser
class ConversationsUser < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :conversation_id, presence: true
  validates :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :author_id, presence: true
  validates :conversation_id, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :conversations_users
  has_many :conversations, through: :conversations_users

  validates :user_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def show
    @conversation = Conversation.find(params[:id])
    @current_user = User.find(params[:current_user])
  end

  def create
    convo = Conversation.create!
    params[:participants].each do |user_id|
      ConversationsUser.create!(
        conversation: convo,
        user_id: user_id
      )
    end

    redirect_to conversation_path(id: convo.id, current_user: params[:current_user])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    Message.create!(
      author_id: params[:author_id],
      conversation_id: params[:conversation_id],
      content: params[:content]
    )

    redirect_to conversation_path(id: params[:conversation_id], current_user: params[:author_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    user_id = params[:id]
    @current_user = User.find(user_id)

    @other_users = User.where.not(id: user_id)
  end

  def new
  end

  def create
    new_user = User.create!(user_name: params[:user_name])

    redirect_to new_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/show.html.erb
<h1>
  Conversation between
  <%= @conversation.participants.pluck('user_name').join(', ') %>
</h1>

<div width="400">
  <div class="participant me">
    <%= @current_user.user_name %>
  </div>

  <%
    @conversation.participants.each do |user|
      next if user == @current_user
  %>
    <div class="participant not-me">
      <%= user.user_name %>
    </div>
 <% end %>

 <%
   @conversation.messages.each do |message|
    classes = ['message']
    classes << if message.author_id != @current_user.id
                 'not-me'
               else
                 'me'
               end
 %>
<div class="<%= classes.join(' ')%>">
  <%= message.content %>
</div>
<% end %>
</div>

<%= form_tag(conversation_messages_path(conversation_id: @conversation.id), method: 'post') do %>
  <%= text_area_tag(:content, '', size: '51x4') %>
  <%= hidden_field_tag(:author_id, @current_user.id) %>
  <br />
  <%= submit_tag('Send message') %>
<% end %>

  <script language="javascript">
    setInterval("location.reload();", 20000);
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome to chatter!</h1>

<% if @users.any? %>
  <h2>Who are you?</h2>
  <% @users.each do |user| %>
    <%= link_to user.user_name, user_path(user) %><br />
  <% end %>

  <h2>None of the above?</h2>
<% end %>

<%= link_to "Create new user", new_user_path %>

app/views/users/new.html.erb
<h1>Create new user</h1>

<%= form_tag(users_path, method: 'post') do %>
  <%= label(:user_name, 'User name:') %>
  <%= text_field_tag('user_name') %>
  <br />
  <%= submit_tag('Create') %>
<% end %>

app/views/users/show.html.erb
<h1>Hi <%= @current_user.user_name %>!</h1>

<h2>Continue existing conversation:</h2>
<% @current_user.conversations.each do |convo| %>
  <%= link_to convo.participants.map(&:user_name).join(' - '), conversation_path(id: convo.id, current_user: @current_user.id) %><br />
<% end %>

<h2>New conversation:</h2>
<% @other_users.each do |user| %>
  <%= link_to(
    user.user_name,
    conversations_path(params: {
      participants: [@current_user.id, user.id ],
      current_user: @current_user.id
    }),
    method: :post
  ) %>
  <br />
<% end %>